name: cnet_web_services
description: C-Net Web Services mobile app for Android and iOS.
publish_to: 'none'
version: 1.1.0+2

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  url_launcher: ^6.3.1
  flutter_secure_storage: ^9.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.8

flutter:
  uses-material-design: true

flutter_native_splash:
  color: "#061D36"
  image: assets/branding/splash_logo.jpeg
  color_dark: "#061D36"
  image_dark: assets/branding/splash_logo.jpeg
  android_12:
    color: "#061D36"
    image: assets/branding/app_icon.png
    color_dark: "#061D36"
    image_dark: assets/branding/app_icon.png
